### ISSUE TITLE
Logging workload crashes

### ISSUE THREAD

**Issue by ertugrulaypek** [dimstav23/GDPRuler#44]
With the latest [PR](https://github.com/dimstav23/GDPRuler/pull/42), running a workload with logging enabled fails with segmentation fault. Digging deeper, I see that sometimes the _log_file_ [here](https://github.com/dimstav23/GDPRuler/blob/main/controller/source/logging/logger.hpp#L72) becomes null which should not be the case. It happens randomly.

**Steps to recreate**

1. Run the db instance: `./build/rocksdb_server 15001 ./db`
2. Run the controller: `python3 GDPRuler.py --config ./configs/owner_policy.json --db rocksdb`
3. Run the client: `python3 client.py --workload ./workload_traces/workload_monitor_50 --clients 2`

**Comment by dimstav23** [comment]
This issue exists indeed. 
It can be reproduced even with smaller workloads when the `monitor` is set to `true` from the default user config.
The controller returns an error message for `Too many open files` which means that the either the socket or the logs file descriptors are not closed properly.

Status: Investigation in progress.
